### ISSUE TITLE
Unused? Reference to Arduino_Sensor.h

### ISSUE THREAD

**Issue by vogt31337** [adafruit/Adafruit_Si5351_Library#1]
Hi!

I just found out that this project doesn't compile due to an maybe unused reference. In file Adafruit_SI5351.h line 44:
#include <Adafruit_Sensor.h>

which doesn't seem to be used anywhere, after commenting out everything compiled nicely.
So maybe you could update the code :)

Thx and cool project!

**Comment by microbuilder** [comment]
Removed, thanks.  That was a leftover from early development.
