### ISSUE TITLE
divider is limited to 3 < div < 901 while AN619 and AN1234 state a range of 8+1/xxx  to 2048

### ISSUE THREAD

**Issue by thefloe1** [adafruit/Adafruit_Si5351_Library#8]
https://github.com/adafruit/Adafruit_Si5351_Library/blob/f0e1b4a4d7acdb29b26e11c23665e66e28f3fe2f/Adafruit_SI5351.cpp#L401

divider is limited to 3 < div < 901 while AN619 and AN1234 state a range of 8+1/xxx  to 2048

**Comment by sx107** [comment]
Not exactly. AN619. page 2:

> Valid Multisynth divider ratios are 4, 6, 8, and any fractional value between 8 + 1/1,048,575 and 2048.

Multisynth integer divisor can be less than 8: 4 or 6. In my experience, 4 or 6 works if the fractional part is set to 0/1, regardless of the multisynth working in fractional or integer mode.

**Comment by thefloe1** [comment]
right, sorry marked the wrong line here. Should have been line 402 and the upper limit is the main concern:

https://github.com/adafruit/Adafruit_Si5351_Library/blob/f0e1b4a4d7acdb29b26e11c23665e66e28f3fe2f/Adafruit_SI5351.cpp#L402

**Comment by caternuson** [comment]
Related:
https://github.com/adafruit/Adafruit_CircuitPython_SI5351/issues/18

**Comment by thefloe1** [comment]
I created a pull request to change the upper limit to 2048

**Comment by stoltzmr** [comment]
Hi Team, how can this update also be applied to Arduino Library? It has been updated in Raspberry Pi library v 1.2.7.

**Comment by ladyada** [comment]
you can test this PR
https://github.com/adafruit/Adafruit_Si5351_Library/pull/10/files

**Comment by stoltzmr** [comment]
This works! Thanks so much @ladyada
